version: 0.0
os: windows
files:
  - source: \DSCC_CW1_5995_front\
    destination: c:\inetpub\wwwroot\
  
hooks:
  BeforeInstall:
    - location: \deletewebsite.bat
      timeout: 180
      runas: administrator
  AfterInstall:
    - location: \installwebsite.ps1
      timeout: 180
      runas: administrator

